src/Entity/Actualite.php
<?php

namespace App\Entity;

use App\Repository\ActualiteRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ActualiteRepository::class)
 */
class Actualite
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */


    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message=" this field is required ")
     */
    private $titre_article;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message=" this field is required ")
     */
    private $type_sport;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message=" this field is required ")
     */
    private $contu_article;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message=" this field is required ")
     */
    private $video;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $jaime;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $jaimepas;
    /**
     * @ORM\ManyToOne(targetEntity=Commentaire::class, inversedBy="Actualite")
     */
    private $Commentaire;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitreArticle(): ?string
    {
        return $this->titre_article;
    }

    public function setTitreArticle(string $titre_article): self
    {
        $this->titre_article = $titre_article;

        return $this;
    }

    public function getTypeSport(): ?string
    {
        return $this->type_sport;
    }

    public function setTypeSport(string $type_sport): self
    {
        $this->type_sport = $type_sport;

        return $this;
    }

    public function getContuArticle(): ?string
    {
        return $this->contu_article;
    }

    public function setContuArticle(string $contu_article): self
    {
        $this->contu_article = $contu_article;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getVideo(): ?string
    {
        return $this->video;
    }

    public function setVideo(string $video): self
    {
        $this->video = $video;

        return $this;
    }

    public function getJaime(): ?int
    {
        return $this->jaime;
    }

    public function setJaime(?int $jaime): self
    {
        $this->jaime = $jaime;

        return $this;
    }

    public function getJaimepas(): ?int
    {
        return $this->jaimepas;
    }

    public function setJaimepas(?int $jaimepas): self
    {
        $this->jaimepas = $jaimepas;

        return $this;
    }
    public function getCommentaire(): ?Commentaire
    {
        return $this->Commentaire;
    }

    public function setCommentaire(?Commentaire $Commentaire): self
    {
        $this->Commentaire = $Commentaire;

        return $this;
    }
}

src/Form/ActualiteType.php
<?php

namespace App\Form;

use App\Entity\Actualite;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ActualiteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre_article')
            ->add('type_sport')
            ->add('contu_article')


            ->add('image',FileType::class,[
                'mapped' => false
            ])
            ->add('video')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Actualite::class,
        ]);
    }
}

src/Controller/Admin/ActualiteController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Actualite;
use App\Form\ActualiteType;
use App\Repository\ActualiteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Dompdf\Dompdf;
use Dompdf\Options;

#[Route('/actualite')]
class  ActualiteController extends AbstractController
{
    #[Route('/', name: 'app_actualite_index', methods: ['GET'])]
    public function index(ActualiteRepository $actualiteRepository): Response
    {
        return $this->render('actualite/index.html.twig', [
            'actualites' => $actualiteRepository->findAll(),
        ]);
    }
    #[Route('/front', name: 'front_actualite', methods: ['GET'])]
    public function showfront(ActualiteRepository $actualiteRepository): Response
    {
        return $this->render('actualite/showfront.html.twig', [
            'actualites' => $actualiteRepository->findAll(),
        ]);
    }
    #[Route('/likeEvent/{id}', name: 'likeEvent', methods: ['GET', 'POST'])]
    public function likeEvent(ActualiteRepository $repository , $id )
    {
        $event=$repository->find($id);
        $new=$event->getJaime() + 1;
        $event->setJaime($new);
        $this->getDoctrine()->getManager()->flush();

        return $this->redirectToRoute('front_actualite');
    }

    #[Route('/dislikeEvent/{id}', name: 'dislikeEvent', methods: ['GET', 'POST'])]
    public function dislikeEvent(ActualiteRepository $repository , $id )
    {
        $event=$repository->find($id);
        $new=$event->getJaimepas() + 1;
        $event->setJaimepas($new);
        $this->getDoctrine()->getManager()->flush();

        return $this->redirectToRoute('front_actualite');
    }
    #[Route('/new', name: 'app_actualite_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ActualiteRepository $actualiteRepository): Response
    {
        $actualite = new Actualite();
        $form = $this->createForm(ActualiteType::class, $actualite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $uploadedFile = $form['image']->getData();
            $filename = md5(uniqid()).'.'.$uploadedFile->guessExtension();
            $uploadedFile->move($this->getParameter('upload_directory'),$filename);
            $actualite->setImage($filename);
            $actualiteRepository->add($actualite);
            return $this->redirectToRoute('app_actualite_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('actualite/new.html.twig', [
            'actualite' => $actualite,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_actualite_show', methods: ['GET'])]
    public function show(Actualite $actualite): Response
    {
        return $this->render('actualite/show.html.twig', [
            'actualite' => $actualite,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_actualite_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Actualite $actualite, ActualiteRepository $actualiteRepository): Response
    {
        $form = $this->createForm(ActualiteType::class, $actualite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $actualiteRepository->add($actualite);
            return $this->redirectToRoute('app_actualite_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('actualite/edit.html.twig', [
            'actualite' => $actualite,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_actualite_delete', methods: ['POST'])]
    public function delete(Request $request, Actualite $actualite, ActualiteRepository $actualiteRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$actualite->getId(), $request->request->get('_token'))) {
            $actualiteRepository->remove($actualite);
        }

        return $this->redirectToRoute('app_actualite_index', [], Response::HTTP_SEE_OTHER);
    }
    /**
     * @Route("/DownloadActualiteData", name="DownloadActualiteData")
     */
    public function DownloadActualiteData(actualiteRepository $repository)
    {
        $produits=$repository->findAll();

        // On définit les options du PDF
        $pdfOptions = new Options();
        // Police par défaut
        $pdfOptions->set('defaultFont', 'Arial');
        $pdfOptions->setIsRemoteEnabled(true);

        // On instancie Dompdf
        $dompdf = new Dompdf($pdfOptions);
        $context = stream_context_create([
            'ssl' => [
                'verify_peer' => FALSE,
                'verify_peer_name' => FALSE,
                'allow_self_signed' => TRUE
            ]
        ]);
        $dompdf->setHttpContext($context);

        // On génère le html
        $html = $this->renderView('Actualite/download.html.twig',
            ['Actualite'=>$Actualite ]);


        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();

        // On génère un nom de fichier
        $fichier = 'Tableau des Actualites.pdf';

        // On envoie le PDF au navigateur
        $dompdf->stream($fichier, [
            'Attachment' => true
        ]);

        return new Response();
    }
}

templates/actualite/_delete_form.html.twig
<form method="post" action="{{ path('app_actualite_delete', {'id': actualite.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ actualite.id) }}">
    <button class="btn">Delete</button>
</form>

templates/actualite/_form.html.twig
{{ form_start(form,{'attr':{'novalidate':'novalidate'}}) }}


<hr class="invis">

<div class="row">
    <div class="col-md-6 col-sm-12">
        <label class="control-label">Titre Article</label>
        {{ form_widget(form.titre_article,{'attr':{'class':'form-control'}}) }}
        {% if not form.titre_article.vars.valid %}
        <div class="alert alert-danger">
            {{ form_errors(form.titre_article) }}
        </div>
        {% endif %}
    </div>
</div><!-- end row -->
<hr class="invis">
<div class="row">
    <div class="col-md-6 col-sm-12">
        <label class="control-label">Type</label>
        {{ form_widget(form.type_sport,{'attr':{'class':'form-control'}}) }}
        {% if not form.type_sport.vars.valid %}
        <div class="alert alert-danger">
            {{ form_errors(form.type_sport) }}
        </div>
        {% endif %}
    </div>
</div><!-- end row -->
<hr class="invis">

<div class="row">
    <div class="col-md-6 col-sm-12">
        <label class="control-label">Content</label>
        {{ form_widget(form.contu_article,{'attr':{'class':'form-control'}}) }}
        {% if not form.contu_article.vars.valid %}
        <div class="alert alert-danger">
            {{ form_errors(form.contu_article) }}
        </div>
        {% endif %}
    </div>
</div><!-- end row -->
<hr class="invis">
<div class="row">
    <div class="col-md-6 col-sm-12">
        <label class="control-label">Video</label>
        {{ form_widget(form.video,{'attr':{'class':'form-control'}}) }}
        {% if not form.video.vars.valid %}
        <div class="alert alert-danger">
            {{ form_errors(form.video) }}
        </div>
        {% endif %}
    </div>
</div><!-- end row -->


<hr class="invis">

<div class="row">
    <div class="col-md-12 col-sm-12">
        <label class="control-label">Image <small>Please add a your Image.</small></label>
        <div class="fileupload fileupload-new" data-provides="fileupload">
            <div class="fileupload-preview thumbnail"></div>
            <br>
            <span class="btn btn-default btn-file">
                                                    <span class="fileupload-new">Select image</span>
                                                    <span class="fileupload-exists">Change</span>
                                                     {{ form_widget(form.image) }}
                                                </span>
            <a href="#" class="btn btn-default fileupload-exists" data-dismiss="fileupload"><i class="fa fa-close"></i></a>
        </div>
    </div>
</div><!-- end row -->


<hr class="invis">
    {{ form_widget(form) }}
    <button class="btn btn-primary btn-block">{{ button_label|default('Submit Form') }}</button>
{{ form_end(form) }}

templates/actualite/download.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Tableau des Actualite</title>
</head>
<body >
<h1 style="text-align: center; color: red">unedeux</h1>
<h2 style="text-align: center">Tableau des Actualite</h2>

<table border="1">
    <thead>
    <tr>

        <th ></th>

        <th >titrearticle	</th>
        <th >typesport </th>
        <th> description </th>
        <th> video</th>


    </tr>
    </thead>
    <tbody>
    {% for p in produits %}
        <tr>
            <td>{{ p.titre_article }}</td>
            <td>{{ p.type_sport }}</td>
            <td>{{ p.contu_article }}</td>

            <td>{{ p.video }}</td>

        </tr>
    {% endfor %}
    </tbody>
</table>


</body>
</html>

templates/actualite/edit.html.twig
{% extends 'front/layout/base.html.twig' %}

{% block body %}
    <h1>Edit Actualite</h1>

    {{ include('actualite/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_actualite_index') }}">back to list</a>

    {{ include('actualite/_delete_form.html.twig') }}
{% endblock %}

templates/actualite/index.html.twig
{% extends 'admin/layout/base.html.twig' %}
{% block body %}
    <h1>Actualite index</h1>
    <div>
        <p style="100px" > <input  id="myInput"  type="text" placeholder="search">
            <img src="https://img.icons8.com/nolan/344/google-web-search.png" style="width:50px;height:50px;"/></p>

    </div>

    <table class="table">
        <thead>
            <tr>

                <th>Titre_article</th>
                <th>Type_sport</th>
                <th>Contu_article</th>
                <th>Image</th>
                <th>Video</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        <tbody>
        <tbody>
        <tbody id="myTable">
        {% for actualite in actualites %}
            <tr>
              
                <td>{{ actualite.titreArticle }}</td>
                <td>{{ actualite.typeSport }}</td>
                <td>{{ actualite.contuArticle }}</td>
                <td>{{ actualite.image }}</td>
                <td>{{ actualite.video }}</td>
                <td>
                    <a href="{{ path('app_actualite_show', {'id': actualite.id}) }}">show</a>
                    <a href="{{ path('app_actualite_edit', {'id': actualite.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        <tbody id="search">

        </tbody>
        </tbody>
    </table>

    <a href="{{ path('app_actualite_new') }}">Create new</a>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function(){
            $("#myInput").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function() {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
{% endblock %}

templates/actualite/new.html.twig
{% extends 'front/layout/base.html.twig' %}
{% block body %}
    <h1>Create new Actualite</h1>

    {{ include('actualite/_form.html.twig') }}

    <a href="{{ path('app_actualite_index') }}">back to list</a>
{% endblock %}

templates/actualite/show.html.twig
{% extends 'front/layout/base.html.twig' %}

{% block body %}
    <h1>Actualite</h1>

    <table class="table">
        <tbody>

           
            <tr>
                <th>Titre_article</th>
                <td>{{ actualite.titreArticle }}</td>
            </tr>
            <tr>
                <th>Type_sport</th>
                <td>{{ actualite.typeSport }}</td>
            </tr>
            <tr>
                <th>Contu_article</th>
                <td>{{ actualite.contuArticle }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td><img class="img-fluid w-100" src="{{ asset('images/actualite/'~actualite.image) }}"
                                 alt=""></td>
            </tr>
            <tr>
                <th>Video</th>
                <td>{{ actualite.video }}</td>
            </tr>
            <tr>
                <th>Commentaire<th>
                <th><form method="post" action="traitement.php">
                        <p><input type="text" name="pseudo" /></p>
                    </form></th>

                <td>{{ actualite.Commentaire }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_actualite_index') }}">back to list</a>

    <a href="{{ path('app_actualite_edit', {'id': actualite.id}) }}">edit</a>

    {{ include('actualite/_delete_form.html.twig') }}
{% endblock %}

templates/actualite/showfront.html.twig
{% extends 'front/layout/base.html.twig' %}
{% block body %}
<div class="col-lg-9 col-md-9 col-xl-9 col-12">
    <div class="row">
        {% for actualite in actualites %}
            <a href="{{ path('app_actualite_show', {'id': actualite.id}) }}">

                <div class="col-lg-4 col-md-6">
                    <div class="single-product">
                        <div class="product-img">
                            <img class="img-fluid w-100" src="{{ asset('images/actualite/'~actualite.image) }}"
                                 alt="">
                            <div class="product-btm">
                                <div class="mt-3">
                                    <span class="mr-4">{{ actualite.typeSport }}</span>
                                </div>
                            </div>
                        </div>
                        <a href="{{ path('likeEvent',{'id':actualite.id}) }}" >Like({{ actualite.jaime }})</a>
                         <a href="{{ path('dislikeEvent',{'id':actualite.id}) }}" >Dislike({{ actualite.jaimepas }})</a>
                    </div>
                     
                </div>
 

                      
            </a>

        {% endfor %}
    </div>

    <a href="{{ path('app_actualite_new') }}">Create new</a>
    <!--Start of Tawk.to Script-->
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/625ba0ab7b967b11798b1546/1g0qun82i';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->
{% endblock %}